reanahub/reana-server

docs/openapi.json, reana_server/api_client.py, reana_server/openapi_connections/reana_workflow_controller.json, reana_server/rest/analyses.py, scripts/generate_openapi_spec.py
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>
=> api: add seeding endpoint

docs/openapi.json, reana_server/openapi_connections/reana_workflow_controller.json, reana_server/rest/analyses.py
* Updates to lastest `rwc` OpenAPI version.
* Create analysis doens't start the workflow straight away, now it creates it in DB
and bootstraps the working space.
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>
=> api: modify create analysis endpoint

docs/openapi.json, reana_server/rest/analyses.py
* replace hardcoded default values for `user` and `organization` with
values obtained from request send by reana-client when listing analyses.
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>
=> api: parameters from client when getting analyses

reana_server/rest/analyses.py
* After v0.0.1 `parameters` key lives under `inputs`.
=> api: update to latest reana spec

docs/openapi.json, reana_server/openapi_connections/reana_workflow_controller.json, reana_server/rest/analyses.py
* Standardizes the way of catching `Bravado` exceptions so messages
are propagated through the REST APIs. (addresses reanahub/reana-client#83).
=> api: standardize error handling

docs/openapi.json, reana_server/openapi_connections/reana_workflow_controller.json, reana_server/rest/analyses.py, reana_server/utils.py
* Add support for specifying a name for a workflow
when creating the workflow.
(closes reanahub/reana-client#70)
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>
=> api: support specifying workflow run name

reana_server/cli.py
* Forces exit code on commands so when server is brought up by
Kubernetes and database is not ready it fails and restarts
the service, hence retrying until database is ready.
=> cli: force exit 1 when commands fail

docs/openapi.json, reana_server/rest/workflows.py
I found some typos in the specification of the API.
Additionally, I saw the following inconsistencies:
- Fields regarding the `Organization`, which I think is in process to be removed.
- Some examples contains the `status` = `waiting`, even if the possible states are: `running`, `failed`, `created` and `finished`
=> api: fixing specification

reana_server/rest/workflows.py
* FIXES when sending empty parameters None was passed to Bravado,
serializing the parameters field as None. An empty dict is passed
instead.
Connects reanahub/reana-workflow-engine-serial#27.
=> api: send empty dict when there are no params

Dockerfile, setup.py
* Uses only `setup.py` to install REANA-Commons and REANA-DB dependencies and
introduced upper boundary for their versions. (addresses reanahub/reana#80)
* Removes installation of their `master` versions from `Dockerfile`.
(closes #85)
=> installation: setup.py for REANA-Commons and REANA-DB

reana_server/version.py, setup.py
* Introduces more upper boundary limits for selected important
dependencies (Bravado, Celery) for the cluster components.
(addresses reanahub/reana#80)
=> installation: more version limits

docs/openapi.json, reana_server/api_client.py, reana_server/cli.py, reana_server/rest/workflows.py, reana_server/scheduler.py, setup.py, tests/test_scheduler.py
* Adds scheduler.py with WorkflowExecutionScheduler class,
responsible for consuming the workflow-submission queue and
schedule the execution of workflows based on priority and
system availability.
* Adds WorkflowSubmissionPublisher to do the publishing of the
incoming workflow submissions to the corresponding message queue.
* Separates start_workflow from set_workflow_status.
Connects https://github.com/reanahub/reana/issues/119
=> global: workflow execution scheduler

docs/openapi.json, reana_server/rest/users.py, reana_server/rest/workflows.py, tests/test_views.py
Adds a temporary authentication endpoint.
Adds a redirection to the auth endpoint when the user tries to
download a resource without the access token.
Provides instruction to the user on how access resources.
Addresses #143
Signed-off-by: leticia <leticia.farias.wanderley@cern.ch>
=> api: redirect to authentication temporary endpoint

reana_server/cli.py, reana_server/config.py, setup.py
* All API calls are failing because the correct allowed host
should be set in every installation. To facilitate development
this configuration is not set, and documents that it should be
used in production.
* Upgrades Invenio dependencies.
* Updates CLI documentation.
=> config: remove allowed_hosts config

Dockerfile, docs/openapi.json, reana_server/config.py, reana_server/rest/workflows.py, reana_server/utils.py, tests/test_views.py
* After the findings in
https://github.com/diegodelemos/client-server-flask-big-file-uploads
it is clear we have to move from multipart uploads, this commit changes
the API description.
* Describing file content in request body, more here
https://swagger.io/docs/specification/describing-request-body/file-upload/.
Addresses reanahub/reana-client#302.
=> api: stream file uploads using request.stream

.travis.yml, setup.py
* Declare supported Python-3.6 version only as this is the one used in
Dockerfile and the one tested on Travis CI.
* Addresses reanahub/reana-client#329
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>
=> installation: Python-3.6 cleanup

docs/openapi.json, reana_server/config.py, reana_server/rest/gitlab.py, reana_server/rest/users.py
closes #175
related to https://github.com/reanahub/reana-ui/pull/44
<details>
<summary>Old approach</summary>
Probably not the most elegant solution.
Another solution would be having the redirect hardcoded like:
```python
...
return make_response(redirect("http://{}:3000/projects".format(REANA_URL)), 201
```
but it's not amazing either because of `http` and `:3000` bits.
Any ideas welcomed 🙏 
</details>
New solution: The backend is in charge of doing the redirection to GitLab firstly and once the authorization succeeded, redirect back to the UI.
=> gitlab: redirect to projects page

Dockerfile, scripts/setup
* Default Dockerfile command is used to run in production mode
(uWSGI). We change the command to write the start-up logs to
a file so we do not expose DB details on pod logs
(closes #193).
* Removes access commands as we are not using Invenio-Access for
speed up (closes #193).
=> dockerfile: silence start-up logs from prod

reana_server/cli.py
* REANA-Cluster is being deprecated so we are removing all references
to it (closes reanahub/reana#238).
=> docs: remove reana-cluster references

setup.py
* New version of Flask-Login (0.5.0) exposes a bug in Flask-Security
(https://github.com/mattupstate/flask-security/issues/681) which
causes errors on endpoints which receive a JSON list in the
body of the request.
=> installation: pin Flask-Login

setup.py
* Newer Flask-CeleryExt specifies and upper limit for Celery. This
causes an upper limit to Kombu (`<4.4`). In REANA we do not use
Celery, we just rely on it because Invenio-Base depends on it,
and we depend on Invenio-Base. But we do heavily rely on Kombu
and our limits are `'kombu>=4.6,<4.7'`. So we pin to this specific
Flask-CeleryExt version to be open ended on Kombu from Invenio side
so we specify the correct version on REANA (on REANA-Commons to
be more correct).
=> installation: pin Flask-CeleryExt

reana_server/rest/workflows.py, tests/test_views.py
closes reanahub/reana-client#403
Avoids downloading unexisting files getting a successful message.
**Before**
```console
$ reana-client download unexisting.txt -w roofit 
File unexisting.txt downloaded to /Users/marco/code/reanahub/reana-demo-root6-roofit
$ cat unexisting.txt
{
"message": "unexisting.txt does not exist."
}
```
=> rest: return status code coming from r-w-c

reana_server/reana_admin.py, setup.py
Command that lists user quotas. Since user's `fullname` and `username` is currently not asked in the sign up form I exchanged `NAME` for `id` and `email`. If no additional options, it prints all user. However alike `user-list` you can filter the output by id, email and user access token.
Example output:
```
ID                                     EMAIL              CPU-USED   CPU-LIMIT   DISK-USED   DISK-LIMIT
00000000-0000-0000-0000-000000000000   adlintul@cern.ch   2499       0           24K         0    
```
Closes #284
=> reana-admin: list quota usage of users

requirements.txt, setup.py
Celery 5.0.0+ requires kombu<6.0,>=5.0.0 and we have kombu pinned
in reana-commons to kombu>=4.6,<4.7.
https://github.com/reanahub/reana-commons/blob/c59decba74ed09161d0e0107c1cc34c22ca6cde0/setup.py#L47
=> setup: pin celery version <5

docs/openapi.json, reana_server/reana_admin.py, reana_server/rest/workflows.py, requirements.txt, scripts/generate_openapi_spec.py, setup.py
* Shows disk usage format either in raw (bytes) or humand-friendly
format (closes reanahub/reana-server#296).
=> rest: simplify disk usage format

reana_server/rest/workflows.py, reana_server/utils.py
Adds reading the type of the workflow (Serial, CWL or Yadage) when restarting it
1. From reana specification if provided
2. From the original workflow
This allows you to restart workflow of different types in the same workspace.
Adds the operational option `accept_metadir ` which allow overwriting the yadage meta directory _yadage (necessary if you want to restart a yadage workflow in a yadage workspace).
closes reanahub/reana-server#293
=> Allow restart with different languages in same workspace

CHANGES.rst, reana_server/config.py
* Addresses reanahub/reana#286.
=> config: increment default rate limiting

reana_server/reana_admin.py, reana_server/status.py, reana_server/utils.py
- Formatted quota usage status report data into readable ASCII tables.
- Fulfilled [these](https://github.com/reanahub/reana-server/issues/330#issuecomment-736308849) requirements
Steps to test:
- Update `helm/reana/values.yaml` in `reanahub/reana` in order to send notification emails:
```python
notifications:
enabled: true
email_config: {}
system_status: "*/3 * * * *"
email_config:
receiver: admins@reana.cern.ch
sender: notifications@reana.cern.ch
```
- Redeploy the cluster
- Populate some test data
- Open `invenio-shell`: ```kubectl exec -i -t deployment/reana-server -c rest-api -- invenio shell```
- Copy the following:
```python
from reana_db.models import User, UserResource, Resource, ResourceType
from reana_db.database import Session
s = Session()
cpu_id = …
```
=> cli: improved quota usage system status report

CHANGES.rst, reana_server/templates/emails/token_request.txt
Adds an explicit command how to obtain administration credentials when
granting/revoking user tokens.
=> templates: enriched instructions for granting user tokens

CHANGES.rst, reana_server/rest/workflows.py
addresses https://github.com/reanahub/docs.reana.io/issues/23
While testing [script](https://forum.reana.io/t/python-api-to-run-workflows-on-reana/19/2) to run workflows from `reana-client` Python API, I noticed that it crashed since `operational_options` was not specified. This is a quick fix to address this problem
=> rest: improve start workflow endpoint to work with unspecified operational_options parameter

CHANGES.rst, reana_server/config.py, reana_server/scheduler.py
* Stops relaying on Kubernetes API calls to determine number of
running workflows. This tecnique is not reliable anymore when
``REANA_RUNTIME_KUBERNETES_KEEP_ALIVE_JOBS_WITH_STATUSES`` is
set since jobs will be kept for debugging, therefore
counting as "running" since they didn't complete their execution.
Since querying for jobs is not possible another path was explored
which was, listing the pods with label `reana_workflow_mode=batch`.
However, this is not reliable either due to race condition:
- Querying jobs worked because we were creating a job
(atomic operation in etcd/DB) and then consulting the API
(reading from etcd/DB).
- Querying pods doesn't work because their creation is not
happening at job creation time. The time between creating
a job and pods to be spawned produces a race …
=> scheduler: read running workflows count from DB

docs/openapi.json, reana_server/factory.py, reana_server/reana_admin.py, reana_server/rest/status.py, reana_server/status.py, requirements.txt, setup.py
closes reanahub/reana#501
closes reanahub/reana-ui#183
If `kubectl top nodes` doesn't work for you, it's because you need  `metrics-server` installed.
```console
$ kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
$ kubectl edit -n kube-system deployment/metrics-server
```
⚠️ Tests not passing due to missing [`reana-commons` release](https://github.com/reanahub/reana-commons/pull/262).
```console
kubectl exec -ti deployment/reana-server -- flask reana-admin status-report --admin-access-token $REANA_ACCESS_TOKEN 
```
=> system-status: enrich with node, pod & job info

CHANGES.rst, Dockerfile, reana_server/complexity.py, reana_server/config.py, reana_server/rest/workflows.py, reana_server/scheduler.py, reana_server/status.py, requirements.txt, setup.py, tests/test_complexity.py
closes https://github.com/reanahub/reana-server/issues/358
This PR tweaks start_workflow() endpoint to estimate and store workflow complexity in the database. The reason behind storing this value in the database is to make scheduling process a bit lighter. If the logic would be there, it would mean additional calls to db (to fetch workflow spec, etc.) and complexity calculation each time the workflow reaches consumer (it can be rescheduled multiple times).
Complexity estimation code is taken from this [PR](https://github.com/reanahub/reana-client/pull/516) with the only changes being made [here](https://github.com/reanahub/reana-server/pull/366/files#diff-dd451815d7362d3092b6e4d2bc6880a2fe0698d82d2415e90b8adc23181eb3faR20-R35) to simply calculate memory needed for all initial jobs and to …
=> scheduler: prioritize workflows in the queue by complexity

reana_server/config.py, reana_server/scheduler.py, tests/test_complexity.py, tests/test_scheduler.py
Rely on the default Helm k8s memory limit instead.
closes reanahub/reana#509
=> config: remove default k8s memory limit

reana_server/scheduler.py
`workflow_min_job_memory` is equal to [0 on fifo mode](https://github.com/reanahub/reana-server/blob/master/reana_server/utils.py#L104-L107)
=> scheduler: skip available node memory calculation on fifo strategy

docs/openapi.json, reana_server/factory.py, reana_server/rest/workflows.py, reana_server/rest/workspaces.py, requirements.txt, setup.py
Goes on top of reanahub/reana-client#545 PR set, and reanahub/reana#532 PR set
Closes reanahub/reana-client#546
=> workflows: add validate function to workspace_root_path 

reana_server/complexity.py, requirements.txt, setup.py, tests/test_complexity.py
The logic of this estimator class is a bit different than the other workflow engines
as it relies on the `dependencies` between jobs that the Snakemake DAG class calculates
(logic implemented in `reana-commons`). From that information, we extract the maximum
number of jobs that can run in parallel and their assigned kubernetes memory limit to
estimate the complexity tuple with the maximum amount of memory to allocate.
closes #392
Depends on https://github.com/reanahub/pytest-reana/pull/89 release
~~Depends on https://github.com/reanahub/reana-commons/pull/300 release~~
**To test:**
1. Change [REANA scheduling policy](https://github.com/reanahub/reana/blob/5c240525313bfef4a49c6db11c12433fbeb51029/helm/reana/values.yaml#L69) to balance and redeploy your cluster:
```diff
diff --git …
```
=> snakemake: add complexity estimator class

reana_server/scheduler.py, setup.py
closes https://github.com/reanahub/reana-message-broker/issues/41
While testing https://github.com/reanahub/reana/pull/558 I've noticed that in some cases after killing `reana-message-broker` the queue gets stuck with the following error in the `scheduler`:
```
2021-10-27 12:08:05,443 | root | MainThread | ERROR | Something went wrong while calling RWC :
409 CONFLICT
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/reana_server/scheduler.py", line 143, in on_message
) = current_rwc_api_client.api.set_workflow_status(
File "/usr/local/lib/python3.8/site-packages/bravado/http_future.py", line 271, in result
swagger_result = self._get_swagger_result(incoming_response)
File "/usr/local/lib/python3.8/site-packages/bravado/http_future.py", line 124, in wrapper …
```
=> scheduler: catch rabbitmq message conflict exception

docs/openapi.json, reana_server/cli.py, reana_server/factory.py, reana_server/version.py
closes reanahub#415
This issue appeared because we were `logging` inside [configs](https://github.com/reanahub/reana-server/blob/master/reana_server/config.py#L151) before setting the log level. This resulted in `WARNING` level set to default which was not overridden by `logging.basicConfig(level=REANA_LOG_LEVEL, format=REANA_LOG_FORMAT)` later on.
This PR sets a logging level with force to override it.
=> scheduler: set correct logging level

reana_server/utils.py, tests/test_utils.py
I went with a minimal implementation just to cover the issue, but there are more cases that we do not support and we might consider it in this PR or open an issue for later. What do you think?
I found a [website](http://emailregex.com) with a less strict email regex. In python:
```python
email_regex = r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"
```
This regex covers cases like `john.doe@edu.uni.ch` or `john.doe.boe@example.org` (double dots) that are not covered currently. But it allows for emails like `john..doe@example.org` which are incorrect, etc.
*question(non-blocking):* @mvidalgarcia do you remember what was the goal for email validation? Like being more strict or catching common input mistakes.
closes #422
=> utils: email validation, handle additional cases

CHANGES.rst, docs/openapi.json, reana_server/config.py, reana_server/reana_admin.py, reana_server/rest/users.py, reana_server/version.py
`quota-set` command in `reana_admin` was using resource _name_ for specifying the resource. Currently we have "processing time" as a `cpu` name and "shared storage" as a `disk` name. So one had to do something like this in order to set some quota limits for a specific user:
```
kubectl exec -i -t deployment/reana-server -- flask reana-admin quota-set -r "shared storage" -e audrius.mecionis@gmail.com -l 200 --admin-access-token $REANA_ACCESS_TOKEN 
```
This PR fixes `quota-set`, `quota-resources`, `quota-set-default-limits` commands to use resource types (e.g. disk, cpu) instead of a resource names ("shared storage", "processing time"). In case of same-type-multi-resource setup scenario it will ask for `--resource-name` to specify the exact resource.
To test:
```
$ kubectl exec -i -t …
```
=> reana-admin: use resource type while setting quota limit

reana_server/app.py, reana_server/config.py, reana_server/ext.py, reana_server/rest/workflows.py
closes #417
closes #298
Two scenarios:
1. Debug mode (`invenio run`)
2. Production mode (`uwsgi`)
To switch between scenarios check https://github.com/reanahub/reana/pull/603
In **both** scenarios, perform these steps:
1. Leave reana-server pod logs open in a terminal
```console
$ kubectl logs deployment/reana-server rest-api -f
```
2. Navigate to the different endpoints via UI and CLI, e.g. UI: sign in, go to the status page, etc.; CLI: `reana-client ping/info/run..`
3. Verify that the logs correspond to the network calls
4. Go to a certain endpoint (e.g. [`/api/config`](https://github.com/reanahub/reana-server/blob/0b4229726fb0a354378970350cda7049f05c2b94/reana_server/rest/config.py#L22)) and add some log messages at the beginning of the function
```diff
diff --git …
```
=> ext: enable logging in REANA Invenio app

CHANGES.rst, docs/openapi.json, reana_server/complexity.py, reana_server/config.py, reana_server/utils.py, reana_server/version.py, requirements.txt, setup.py
closes https://github.com/reanahub/reana-server/issues/437
About the issue:
It only appears in the `balanced` scheduling mode and with working Kubernetes metrics-server, probably that's why it slipped through our testing. The root cause of the issue happens [here](https://github.com/reanahub/reana-server/blob/master/reana_server/scheduler.py#L38). In `balanced` mode we also measure if at least one workflow job could be started:
- We take `min_job_memory` [here](https://github.com/reanahub/reana-server/blob/master/reana_server/utils.py#L114) and send it as a param in message header to the scheduler.
- The scheduler [verifies if there are enough memory to execute the job](https://github.com/reanahub/reana-server/blob/master/reana_server/scheduler.py#L32). If not - it reschedules it for …
=> rest: validate Kubernetes job memory limits before publishing workflow

CHANGES.rst, docs/openapi.json, reana_server/api_client.py, reana_server/config.py, reana_server/scheduler.py, reana_server/utils.py, reana_server/version.py, requirements.txt, setup.py, tests/test_scheduler.py
closes #436
**Important:** there are two commits in a not-ready state because I moved some scheduler code to a separate folder. if reviewers will not object to the change, I will squash commits before merging. 
How to test:
1. Checkout all related PRs from the issue description
2. Edit `values-dev.yaml`:
```yaml
components:
reana_server:
image: reanahub/reana-server
environment:
REANA_SCHEDULER_REQUEUE_SLEEP: 5
REANA_SCHEDULER_REQUEUE_COUNT: 10
REANA_WORKFLOW_SCHEDULING_POLICY: "balanced"
...
kubernetes_jobs_memory_limit: 2Gi
kubernetes_jobs_max_user_memory_limit: 24Gi  # this value should be bigger then your available memory
```
3. Re-deploy REANA
4. Set a memory limit for a job in a workflow that still fits within the specified limit but exceeds your machine capacity. For example, …
=> scheduler: add retry mechanism

CHANGES.rst, reana_server/config.py, reana_server/fetcher.py, requirements.txt, setup.py, tests/test_fetcher.py
Closes #441
How to test:
1. Save the following python snippet to a file in the repository's root directory (e.g. `pr445.py`)
```python
import os
import random
import string
from reana_server.fetcher import get_fetcher
from tests.test_fetcher import GIT_URL, GITHUB_REPO_URL, YAML_URL, ZENODO_URL
def random_string():
return "".join(random.choices(string.ascii_lowercase, k=5))
def fetch(url, tmp_dir=None):
if not tmp_dir:
tmp_dir = os.path.join("/tmp", "test-fetcher-{}".format(random_string()))
os.makedirs(tmp_dir)
print(f"Fetching to directory: {tmp_dir}")
fetcher = get_fetcher(url, tmp_dir)
fetcher.fetch()
spec = fetcher.workflow_spec_path()
print(f"REANA workflow specification file: {spec}")
```
2. Execute the saved file in interactive mode: `python -i pr445.py`
3. Call the `fetch` …
=> fetcher: add workflow specification fetcher

CHANGES.rst, Dockerfile, reana_server/rest/info.py, reana_server/rest/workflows.py, reana_server/validation.py, setup.py
closes https://github.com/reanahub/reana-server/issues/442
To test:
- Install `ipython`, local `reana-commons` and `reana-server` into a new virtualenv
- Navigate to `reana-demo-root6-roofit` and launch `ipython`:
```python
import logging
from reana_commons.specification import load_reana_spec
from reana_commons.validation.utils import validate_reana_yaml
from reana_commons.errors import REANAValidationError
from reana_server.validation import (
validate_parameters,
validate_compute_backends,
validate_workspace_path,
)
reana_yaml = load_reana_spec("./reana.yaml")
try:
validate_reana_yaml(reana_yaml)
validate_parameters(reana_yaml)
validate_compute_backends(reana_yaml)
validate_workspace_path(reana_yaml)
except REANAValidationError as e:
logging.error(e)
```
TODO:
=> validation: refactor validation imports

reana_server/config.py, reana_server/fetcher.py, reana_server/rest/launch.py, tests/test_fetcher.py
This PR adds some limitations and checks to the download of files:
- Connection and read timeout
- Limit to the size of the file to be downloaded
- Allow only `http` and `https`
How to test:
Launch this workflow: `https://zenodo.org/record/5752285/files/circular-health-data-processing-master.zip`
In each of these cases, the workflow is not launched and an error is reported:
- Set `FETCHER_MAXIMUM_FILE_SIZE` to a small value (e.g. 1024)
- Remove `https` from `FETCHER_ALLOWED_SCHEMES`
- Set `FETCHER_REQUEST_TIMEOUT` to a small value (e.g. 0.1)
=> fetcher: add limitations to the download of files

docs/openapi.json, reana_server/fetcher.py, reana_server/rest/launch.py, tests/test_fetcher.py
Closes #452
How to test:
Launch some of the example workflows, choosing different workflow specifications, for example:
```
/launch?url=https://zenodo.org/record/5752285/files/circular-health-data-processing-master.zip
/launch?spec=reana.yaml&url=https://zenodo.org/record/5752285/files/circular-health-data-processing-master.zip
/launch?url=https://github.com/reanahub/reana-demo-root6-roofit
/launch?spec=reana.yaml&url=https://github.com/reanahub/reana-demo-root6-roofit
/launch?spec=reana-cwl.yaml&url=https://github.com/reanahub/reana-demo-root6-roofit
```
Note that the last example will fail due to #456
=> rest: add `spec` parameter to launch endpoint

AUTHORS.rst, reana_server/fetcher.py, reana_server/rest/launch.py
Closes #472
How to test:
Launch the following workflows
```
https://github.com/reanahub/reana-demo-root6-roofit/tree/invalid
https://github.com/reanahub/invalid
```
Expected result:
The workflows are not launched and the error messages shown to the user are short and user-friendly
=> rest: improve error messages in `/launch` endpoint

reana_server/config.py, reana_server/fetcher.py, tests/test_fetcher.py
Closes #483
How to test:
- Create a new public repository and push a REANA demo to [gitlab.cern.ch](https://gitlab.cern.ch)
- Launch some workflows using the following URLs:
- URL to the repository
- URL to a specific tag/branch/commit
- URL to the repository's zip archive
Expected result: The workflows are launched and executed correctly
=> fetcher: add support for GitLab URLs

CHANGES.rst, docs/openapi.json, reana_server/config.py, reana_server/version.py
Changes Invenio `oauthclient contrib` to `cern_openid` which enables the new SSO usage.
In order to test:
- Some instructions can be found in [DR docs](https://digital-repositories.web.cern.ch/digital-repositories/common-recipes/cern-oauth/)
- Test application was created in QA environment: https://application-portal-qa.web.cern.ch/manage/08da188d-ef3c-4d9f-8b9d-38ed6f954d58 . Please copy the secrets from there to use it below
- In order to point to QA server please update `OAUTH_REMOTE_REST_APP["params"]` to: 
```
{
"base_url": "https://keycloak-qa.cern.ch/auth/realms/cern",
"access_token_url": "https://keycloak-qa.cern.ch/auth/realms/cern/protocol/openid-connect/token",
"authorize_url": "https://keycloak-qa.cern.ch/auth/realms/cern/protocol/openid-connect/auth",
}
```
- Update …
=> auth: migrate to the new SSO

CHANGES.rst, reana_server/reana_admin/__init__.py, reana_server/reana_admin/cli.py, reana_server/reana_admin/consumer.py, tests/test_cli.py
closes reanahub/reana-message-broker#45
How to test?
0. Unit tests should cover the situation when you specify some `values-to-delete` (using the -v option). So, you should test the interactive way.
1. Bash into r-server `kubectl exec -it deployment/reana-server -- bash`. Run `flask reana-admin consume-queue -q workflow-submission -i`. This command will start listening to messages from the `workflow-submission` queue.
2. Submit some workflows. You will see our consumer picks up some messages (because the scheduler is working at the same time). Use
=> admin: add command to delete messages from queue

reana_server/decorators.py, reana_server/status.py, reana_server/utils.py, requirements.txt, setup.py
closes https://github.com/reanahub/reana-client/issues/607
To test:
- Change [this line](https://github.com/reanahub/reana/blob/master/helm/reana/values.yaml#L145) to `termination_update_policy: "disk,cpu"`
- Redeploy the cluster
- Run some workflows
- Add some quota limits for your user:
- `kubectl exec -i -t deployment/reana-server -- flask reana-admin quota-set -r cpu -e your.email@cern.ch -l 100000`
- `kubectl exec -i -t deployment/reana-server -- flask reana-admin quota-set -r disk -e your.email@cern.ch -l 100000`
- Verify quota limits:
- `kubectl exec -i -t deployment/reana-server -- flask reana-admin quota-usage --admin-access-token $REANA_ACCESS_TOKEN`
- Check if `quota-show` still works as expected: 
- `reana-client quota-show --resource disk -h`
- Try to create a new workflow:
- …
=> rest: more informative output when users exceed quotas

reana_server/reana_admin/check_workflows.py, reana_server/reana_admin/cli.py, reana_server/reana_admin/consumer.py, setup.py
closes #491
You will need to reproduce a few scenarios where workflows end up in sync situations. There are multiple ways to do it and probably some ways we didn't discover yet. Below you can find *one* way to do it for each state.
The message is not published to the `workflow-submission` queue. To do this go to `values-dev.yaml`. Enable "balanced" strategy, and set `kubernetes_jobs_max_user_memory_limit`:
```yaml
components:
reana_server:
image: reanahub/reana-server
environment:
...
REANA_WORKFLOW_SCHEDULING_POLICY: "balanced"
...
kubernetes_jobs_max_user_memory_limit: "4Gi"
```
Go to `helloworld` workflow, set `kubernetes_memory_limit`higher than allowed - `8Gi`. Run the workflow using `reana-client run`. Submission will fail right away but the workflow will end up in the queued state. …
=> admin: add command to detect out-of-sync workflows

CHANGES.rst, reana_server/config.py
- replace int() with float() to allow "1e+06" liek numbers and "infinity"
closes #502
=> config: fix REANA_SCHEDULER_REQUEUE_SLEEP for large numbers

docs/openapi.json, reana_server/rest/workflows.py
Update the list of possible response MIME types of the `download_file` endpoint.
Closes #418
=> rest: update openapi specification of `download_file`

docs/openapi.json, reana_server/rest/gitlab.py, reana_server/rest/info.py, reana_server/rest/workflows.py
Updated api schema for:
- `info` endpoint:
- added `compute_backends` and specified properties for other fields
- `workflows` endpoint:
- enriched `progress` schema, added missing `launcher_url` field
- gitlab `webhook` endpoint:
- changed parameters to from `query` to `path`. `go-swagger` validator gave an error for the specification because of this:
```
the swagger spec at "/home/amecioni/Documents/projects/reana-client-go/reana_server.json" is invalid against swagger specification 2.0. see errors :
- path param "project_id" is not present in path "/api/gitlab/webhook"
- path param "hook_id" is not present in path "/api/gitlab/webhook"
```
=> openapi: updated api schema

CHANGES.rst, reana_server/reana_admin/cli.py, reana_server/reana_admin/retention_rule_deleter.py, tests/conftest.py, tests/test_cli.py
Add command to apply pending retention rules, deleting the necessary files or directories.
How to test:
1. Modify one of the demo examples, defining some retention rules
2. Fake a different current time (e.g. one day in the future)
```diff
--- a/reana_server/reana_admin/cli.py
+++ b/reana_server/reana_admin/cli.py
@@ -748,6 +748,7 @@ def check_workflows(
def retention_rules_apply() -> None:
"""Apply pending retentions rules."""
current_time = datetime.datetime.now()
+    current_time = current_time + datetime.timedelta(days=1)
pending_rules = WorkspaceRetentionRule.query.filter(
WorkspaceRetentionRule.status == WorkspaceRetentionRuleStatus.active,
WorkspaceRetentionRule.apply_on < current_time,
```
3. Run the `retention-rules-apply` command
```
kubectl exec -it deployments/reana-server -- …
```
=> reana-admin: add `retention-rules-apply` command

reana_server/config.py, reana_server/utils.py, reana_server/validation.py, requirements.txt, setup.py, tests/test_validation.py
- if rules are disabled they will not be created in the database; this is easier because we do not need additional code logic to skip rules.
1. Add some retention rules (e.g. root6 workflow):
```diff
diff --git a/reana.yaml b/reana.yaml
index 9b13d45..59c80db 100644
--- a/reana.yaml
+++ b/reana.yaml
@@ -21,6 +21,12 @@ workflow:
kubernetes_memory_limit: '256Mi'
commands:
- root -b -q 'code/fitdata.C("${data}","${plot}")'
+
+workspace:
+  retention_days:
+    results/*.root: 1
+    code/*.C: 1
+
outputs:
files:
- results/plot.png
```
2. Modify values to set default retention period to always keep files:
```diff
diff --git a/helm/reana/values.yaml b/helm/reana/values.yaml
index 4d66cfa..487683b 100644
--- a/helm/reana/values.yaml
+++ b/helm/reana/values.yaml
@@ -13,7 +13,7 @@ eos: …
```
=> workspace retention: allow disabling retention rules

CHANGES.rst, reana_server/reana_admin/check_workflows.py, reana_server/reana_admin/cli.py, tests/test_cli.py
- add possibility to "check-workflows" command to detect out-of-sync interactive sessions.
Session has `created` status in DB when they are open. When it is closed, the record is deleted from the database. It differs from workflow, where deleted workflow is kept in the database.
There are three scenarios:
1. Interactive session is in database, open, and pod exist:
- run some workflow like `helloworld`
- open a session (`reana-client open -w <workflow-name>`)
- ssh into `r-server` using `kubectl exec -i -t <r-server-pod-id> -- /bin/bash`
- run check command `flask reana-admin check-workflows`
- it should pass
2. Interactive session is in DB but pod doesn't exist:
- reuse a session from before
- run `kubectl get deployments` to locate Deployment for interactive session
- delete deployment …
=> admin: detect out-of-sync interactive sessions

CHANGES.rst, reana_server/rest/workflows.py, reana_server/utils.py, tests/test_views.py
- before, "create_workflow" endpoint was not validating REANA specification; this commit adds validation.
- it also fixes some tests as they incorrectly put "workflow_name" in JSON body instead of query string.
closes #468
=> rest: validate REANA specification

reana_server/utils.py
- request.content_length is Optional[int] according to flask docs;
- prevent_disk_quota_exceed was not checking if bytes_to_sum (request.content_length) is not None so "+" operation failed;
closes #498
=> utils: fix empty files upload error

CHANGES.rst, reana_server/rest/workflows.py, tests/test_views.py
- because client doesn't include Yadage specification in "create" endpoint, validation fails;
- workflow validation is moved to "start_workflow" so in case Yadage specification has multiple files, they can be loaded and properly validated.
closes #535
=> rest: remove specification validation from "create" endpoint

docs/openapi.json, reana_server/rest/workflows.py
Some fields of the response of `get_workflow_status` can be `null`.
Closes #538
=> openapi: update schema of `get_workflow_status`

docs/openapi.json, reana_server/rest/workflows.py
closes https://github.com/reanahub/reana-client-go/issues/95
=> openapi: add missing param schema to start_workflow

reana_server/reana_admin/cli.py, reana_server/reana_admin/retention_rule_deleter.py, tests/test_cli.py
closes https://github.com/reanahub/reana-server/issues/555
To test:
- create some workflows with retention rules
- `kubectl exec -i -t deployment/reana-server -c rest-api -- flask reana-admin retention-rules-apply --dry-run`
=> admin: add `--dry-run` option to `retention-rules-apply`

CHANGES.rst, reana_server/reana_admin/cli.py, reana_server/reana_admin/options.py, tests/test_cli.py
closes https://github.com/reanahub/reana-server/issues/556
To test:
- create some workflows with retention rules
- `kubectl exec -i -t deployment/reana-server -c rest-api -- flask reana-admin retention-rules-extend -d 4 -w d171760a-a7db-4270-80fd-dddd526bc20c`
=> admin: add retention-rules-extend command

CHANGES.rst, reana_server/reana_admin/check_workflows.py, reana_server/status.py, scripts/generate_openapi_spec.py
This commit improves how the disk usage summary is formatted in the
system status report. It also removes the size of the users' directory
from the report, as this information is redundant but it takes a lot of
time to be collected.
Closes #573
=> admin: improve disk usage summary in status report

CHANGES.rst, reana_server/reana_admin/cli.py, tests/test_cli.py
Add command to close interactive sessions running longer than a specified number of days.
closes https://github.com/reanahub/reana-workflow-controller/issues/498
=> reana-admin: add interactive-session-cleanup command

requirements.txt, setup.py
This commit downgrades `invenio-i18n` and `invenio-theme`, which were
updated to v2 in 0.9.1a1 (see #581). This solves issues with the
upcoming support to Keycloak SSO (see #513).
=> setup: pin `invenio-i18n` and `invenio-theme` versions

AUTHORS.rst, CHANGES.rst, reana_server/config.py
This PR adds `invenio_oauthclient.contrib.keycloak` and configures a second OAuth app for generic/Keycloak SSO functionality to the server's config.
Fixes #513
=> auth: add `invenio_oauthclient.contrib.keycloak` and configuration for generic SSO login

reana_server/rest/gitlab.py
Use `url_for` to build API URLs. Before, URLs were built in different
ways when creating and retrieving GitLab's webhooks, which sometimes
resulted in having different URLs for the same `create_workflow`
endpoint. This caused already created webhooks not to be recognized by
REANA, as a wrong URL was used to identify them.
Closes #593
=> gitlab: use `url_for` to build API URLs

CHANGES.rst, reana_server/utils.py, tests/test_utils.py
Before this commit, REANA was only checking that the user had at least
one valid token during the authentication process, without checking
whether the provided token was valid or revoked. This meant that users
were able to use revoked tokens, as long as they had at least one other
active token.
This commit fixes this issue by checking that the provided token is
active before proceeding with the authentication process.
=> utils: check token status before authenticating user

reana_server/decorators.py, reana_server/reana_admin/cli.py, reana_server/reana_admin/options.py, reana_server/utils.py, tests/test_cli.py
closes https://github.com/reanahub/reana-server/issues/489
=> admin: standardize --admin-access-token usage

CHANGES.rst, docs/openapi.json, reana_server/config.py, reana_server/rest/info.py
Adds the `maximum_interactive_session_inactivity_period` value to the ones returned by `/api/info`.
Addresses reanahub/reana-client#657
=> rest: add max inactivity period for interactive sessions to info endpoint

docs/openapi.json, reana_server/rest/info.py, requirements.txt, scripts/generate_openapi_spec.py, setup.py
Update to apispec v3, as the version used before is not compatible with
PyYAML v6. This commit also removes the marshmallow plugin for apispec,
as the generated OpenAPI spec is different and causes issues with
reana-client. This is due to the fact that the OpenAPI specifications of
marshmallow schemas are now put inside the global `definitions` object,
instead of being inlined in the endpoint's specification as before.
Closes reanahub/reana-commons#399
=> global: update to apispec v3

CHANGES.rst, docs/openapi.json, reana_server/rest/workflows.py
=> rest: add run_stopped_at to status endpoint

CHANGES.rst, docs/openapi.json, reana_server/rest/launch.py, reana_server/validation.py
In case some warnings are issued when launching a workflow, the `launch` endpoint will now include them in the returned `message`. 
Closes reanahub/reana-client#660.
=> launch: include validation warnings in returned message

docs/openapi.json, reana_server/rest/workflows.py, reana_server/version.py, requirements.txt, scripts/generate_openapi_spec.py, setup.py
- global: prepare for future Flask upgrades
- installation: bump all dependencies
- release: 0.9.1a4
=> release: 0.9.1a4

run-tests.sh, tests/test_deleter.py
Allows execution of selected pytests via PYTESTCMD environment variable. Example: `PYTESTARG="-k test_version" ./run-tests.sh --check-pytest`.
Cleans up running DB container when some pytest segfaults.
Removes forgotten `import wdb` statement that was breaking running tests when only the `.[tests]` installation target is called to set up the test prerequisites.
Closes reanahub/reana#755.
=> tests: allow execution of selected pytests only

docs/openapi.json, reana_server/rest/gitlab.py, reana_server/utils.py, tests/test_views.py
- feat(gitlab): add search query parameter to filter projects (#681)
- feat(gitlab): add support for paginated project list (#681)
BREAKING CHANGE: The REST API endpoint `gitlab_projects` now includes
pagination details.
Closes #518
=> feat(gitlab): add filtering and pagination (#681)

reana_server/config.py, reana_server/utils.py, tests/test_utils.py, tests/test_views.py
=> fix(gitlab): handle pagination of GitLab webhooks (#684)

reana_server/reana_admin/cli.py
Removes hard-coded infrastructure component host name domain "svc.local.cluster" during interactive session clean-up procedures, since this assumption is not really necessary and would not work under some deployment scenarios, such as on SSL-RIVER.
Closes reanahub/reana-commons#457
=> fix(reana-admin): respect service domain when cleaning sessions (#687)

.github/workflows/ci.yml, docs/openapi.json, reana_server/rest/workflows.py, run-tests.sh, tests/test_views.py
Closes reanahub/reana-client#718
=> fix(start): validate endpoint parameters (#689)

docs/openapi.json, reana_server/rest/workflows.py, tests/test_views.py
When starting a new workflow, publish the workflow to the submission
queue instead of executing the workflow immediately by calling
`set_workflow_status` in workflow-controller.
Depends on #689 
Closes #690
=> fix(set_workflow_status): publish workflows to submission queue (#691)

.github/workflows/ci.yml, setup.py
BREAKING CHANGE: drop support for Python 3.6 and 3.7
Closes reanahub/reana#784
=> build(python): drop support for Python 3.6 and 3.7 (#683)

docs/openapi.json, reana_server/gitlab_client.py, reana_server/rest/gitlab.py, reana_server/rest/secrets.py, reana_server/utils.py, setup.py, tests/test_gitlab_client.py, tests/test_views.py
Refactor secrets-related endpoints to adapt to performance-related
refactor of `reana-commons`. Improve validation of endpoints'
parameters.
Closes reanahub/reana-commons#455
=> refactor(secrets): adapt to reana-commons secret-handling changes (#686)

reana_server/reana_admin/cli.py
Closes reanahub/reana-server#693
=> fix(reana-admin): skip retention rules with deleted workspace (#697)

Dockerfile
Pin `setuptools` to the maximum version of 70 to allow working on Ubuntu 20.04 LTS based environments. (New versions of `setuptools` are not compatible.)
Note that this fix is necessary only for the `maint-0.9` branches and the REANA 0.9 release series. In `master` we have switched to Ubuntu 24.04 LTS based environments and Python 3.12 and no pinning is necessary there.
=> build(docker): pin setuptools 70

docs/openapi.json, reana_server/rest/users.py, reana_server/rest/workflows.py, requirements.txt, setup.py, tests/test_cli.py, tests/test_decorators.py, tests/test_deleter.py, tests/test_users.py, tests/test_utils.py, tests/test_views.py
| Command               | Allowed   |
|-----------------------|-----------|
| delete            | ❌        |
| diff                | ✅        |
| logs                  | ✅        |
| restart           | ❌        |
| start             | ❌        |
| status              | ✅        |
| stop              | ❌        |
| share-add         | ❌        |
| share-remove      | ❌        |
| share-status      | ❌        |
| close            | ❌        |
| open              | ❌        |
| download            | ✅        |
| du                  | ✅        |
| ls                   | ✅        |
| mv                 | ❌        |
| prune             | ❌        |
| rm              | ❌        |
| upload            | ❌        |
| retention-rules-list| ✅        |
Closes reanahub/reana-server#651, closes …
=> rest: make details available for shared workflows

AUTHORS.md, docs/openapi.json, reana_server/rest/workflows.py
Related to https://github.com/reanahub/reana/issues/824
Add `live_logs_enabled` parameter to `get_workflow_logs` API endpoint.
=> feat(get_logs): add live_logs_enabled parameter (#705)

AUTHORS.md, docs/openapi.json, reana_server/config.py, reana_server/rest/info.py, reana_server/rest/workflows.py, reana_server/validation.py
This pull request contains the ongoing work of dask integration into REANA.
=> feat(helm): add initial Dask support

docs/openapi.json, reana_server/config.py, reana_server/rest/info.py
=> feat(config): make dask autoscaler configurable

docs/openapi.json, reana_server/config.py, reana_server/rest/info.py
Closes reanahub/reana-workflow-controller#569
=> feat(sessions): add recommended images to info endpoint

docs/openapi.json, reana_server/rest/info.py
Closes reanahub/reana-client#734
=> feat(engines): add workflow engine versions to info endpoint

reana_server/config.py, reana_server/utils.py
This PR is part of harmonizing the treatment of REANA_HOSTNAME accross all REANA components. You can refer to other PRs below.
reanahub/reana#867
reanahub/reana-workflow-controller#630
Closes reanahub/reana#865
=> fix(config): set localhost default value for REANA_HOSTNAME

docs/openapi.json, reana_server/config.py, reana_server/rest/info.py, reana_server/rest/workflows.py, reana_server/validation.py, setup.py
Following the integration of Dask into REANA and discussions with several REANA users, we identified the need to make the number of threads configurable.
This commit adds the number of threads configuration to the `/api/info` endpoint. It also validates that the requested number of threads for a single Dask worker does not exceed the defined upper limit.
Closes reanahub/reana#874
=> feat(config): make number of threads configurable for Dask

.github/workflows/ci.yml, docs/openapi.json, reana_server/config.py, reana_server/rest/info.py, requirements.txt, setup.py
Validate CPU and memory requests/limits for job pods in each step. Expose limits and defaults in `info` endpoint.
Closes reanahub/reana#883
=> feat(rest): add K8s resource requests & limits to info endpoint
