reanahub/reana-server

MANIFEST.in
reana_server/__init__.py
reana_server/factory.py
reana_server/rest/__init__.py
reana_server/rest/ping.py
reana_server/version.py

Comments needed on naming and structure etc.

app: implement app factory pattern

---

MANIFEST.in
reana_server/api_client.py
reana_server/config.py
reana_server/factory.py
reana_server/openapi_connections/reana_workflow_controller.json
reana_server/rest/analyses.py
setup.py

* Adds bravado for automatic OpenAPI client generation. (closes #6)
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>

api: connect to REANA Workflow Controller

---

docs/openapi.json
reana_server/openapi_connections/reana_workflow_controller.json
reana_server/rest/analyses.py

Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>

api: submit reana spec

---

docs/openapi.json
reana_server/openapi_connections/reana_workflow_controller.json
reana_server/rest/analyses.py

* add endpoint to get status of an analysis
(addresses reanahub/reana-client#39)
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>

api: add endpoint to get status of an analysis

---

docs/openapi.json
reana_server/openapi_connections/reana_workflow_controller.json
reana_server/rest/analyses.py

api: add set_analysis_status endpoint

---

docs/openapi.json
reana_server/openapi_connections/reana_workflow_controller.json
reana_server/rest/analyses.py

api: add download analysis output files endpoint

---

docs/openapi.json
reana_server/rest/analyses.py

api: add inputs list endpoint

---

docs/openapi.json
reana_server/rest/analyses.py

api: add outputs list endpoint

---

docs/openapi.json
reana_server/openapi_connections/reana_workflow_controller.json
reana_server/rest/analyses.py

* Includes single endpoint for file seeding and retrieving. Amends current
code accordingly.

api: add seed/list analysis code endpoints

---

.travis.yml
AUTHORS.rst
README.rst
docs/authors.rst
docs/changes.rst
docs/conf.py
docs/contributing.rst
docs/gettingstarted.rst
docs/index.rst
docs/introduction.rst
docs/license.rst
docs/restapi.rst

* Enhances documentation structure, updates author list, updates short
description and feature list.

docs: better structure

---

CHANGES.rst
reana_server/version.py

release: v0.1.0

---

reana_server/version.py

version: post-release bump

---

docs/openapi.json
reana_server/app.py
reana_server/config.py
reana_server/openapi_connections/reana_workflow_controller.json
reana_server/rest/analyses.py

* Squashed version of https://github.com/reanahub/reana-server/pull/34.

cwl: initial integration

---

.gitignore
docs/openapi.json
reana_server/openapi_connections/reana_workflow_controller.json
reana_server/rest/analyses.py

* (closes reanahub/reana-client#75).

api: warn user when workflow can not be started

---

reana_server/rest/analyses.py

rest: fix outputs download

---

AUTHORS.rst
reana_server/version.py

docs: author ORCID links

---

docs/openapi.json
reana_server/openapi_connections/reana_workflow_controller.json
reana_server/rest/analyses.py

Closes https://github.com/reanahub/reana-workflow-controller/issues/84

openapi: workflow-controller spec, logs in status

---

.travis.yml
Dockerfile
docs/openapi.json
reana_server/cli.py
reana_server/config.py
reana_server/factory.py
reana_server/openapi_connections/reana_workflow_controller.json
reana_server/rest/analyses.py
reana_server/rest/users.py
reana_server/utils.py
reana_server/version.py
requirements-dev.txt
setup.py
tests/conftest.py
tests/test_views.py

* ADD REST endpoints for user management.
* ADD cli for the creation of the first user from workflow-controller.

rest: user management

---

Dockerfile
reana_server/cli.py
setup.py

* DB initilisation moved from reana-cluster to server.

db: init db when container starts

---

Dockerfile
reana_server/app.py
setup.py

* (addresses #48)
Doesn't close #48 since this needs to be applied to `job-controller` and `workflow-controller` as well.

docker: run with uwsgi by default

---

Dockerfile
docs/openapi.json
reana_server/cli.py
reana_server/rest/users.py
reana_server/utils.py

Addresses https://github.com/reanahub/reana-client/issues/127
Closes https://github.com/reanahub/reana-server/issues/59

cli: specify token in users create

---

README.rst
docs/openapi.json
reana_server/factory.py
reana_server/rest/workflows.py
reana_server/utils.py

Depends on https://github.com/reanahub/reana-commons/pull/30
Addresses #58 

global: renaming analyses -> workflows

---

docs/openapi.json
reana_server/cli.py
reana_server/rest/users.py
reana_server/rest/workflows.py
reana_server/utils.py
tests/conftest.py
tests/test_views.py

Connects https://github.com/reanahub/reana-client/issues/128

cli: rename REANA_TOKEN to REANA_ACCESS_TOKEN

---

docs/openapi.json
reana_server/cli.py
reana_server/openapi_connections/reana_workflow_controller.json
reana_server/rest/workflows.py
reana_server/utils.py

* Updates RWC OpenAPI spec.
* Simplifies Flask method naming following RWC.
Closes #60

rest: workspace endpoint to manage all files

---

docs/openapi.json
reana_server/app.py
reana_server/cli.py
reana_server/config.py
reana_server/openapi_connections/reana_workflow_controller.json
reana_server/rest/users.py
reana_server/rest/workflows.py
reana_server/utils.py
tests/conftest.py
tests/test_views.py

Connects https://github.com/reanahub/reana-commons/issues/25

global: remove organization

---

reana_server/factory.py
setup.py

* ADD flask-cors to allow for cross origin
AJAX requests.
Closes #68 

global: addition of flask-cors

---

reana_server/rest/workflows.py

Connect https://github.com/reanahub/reana-client/issues/109

rest: optional parameters field in reana_spec_file

---

reana_server/rest/workflows.py

* Renames workflow_status() to get_workflow_status() for consistency

rest: get_ + workflow_status

---

Dockerfile
docs/requirements.txt
reana_server/cli.py
reana_server/factory.py
reana_server/rest/ping.py
reana_server/rest/users.py
reana_server/rest/workflows.py
reana_server/utils.py
requirements-dev.txt
setup.py
tests/conftest.py
tests/test_views.py

installation: REANA-DB and REANA-Commons splitted

---

docs/openapi.json
reana_server/openapi_connections/reana_workflow_controller.json
reana_server/rest/workflows.py

Connects https://github.com/reanahub/reana-client/issues/143

rest: pass parameters in set_workflow_status

---

CHANGES.rst
docs/cli.rst
docs/index.rst
reana_server/cli.py
reana_server/version.py
setup.py

Closes #78 
Closes https://github.com/reanahub/reana-server/issues/57
Waiting for v0.3.0 release of reana-db & reana-commons

release: v0.3.0

---

docs/openapi.json
reana_server/openapi_connections/reana_workflow_controller.json
reana_server/rest/workflows.py

* (closes reanahub/reana-client#162).

rest: harmonise date time format

---

docs/openapi.json
reana_server/rest/workflows.py
tests/conftest.py
tests/test_views.py

* Relays the reana_specification to REANA Workflow Controller in workflow
creation requests.
Connects https://github.com/reanahub/reana-db/issues/12

rest: pass reana_specification to RWC in workflow_create()

---

docs/conf.py
docs/index.rst
docs/openapi.json
reana_server/rest/ping.py
reana_server/rest/workflows.py

* Fix navigation. Harmonise title/description text in Python docstring
and OpenAPI. Amend order in index page. Closes #99

docs: better navigation and synced descriptions

---

AUTHORS.rst
CHANGES.rst
reana_server/version.py
setup.py

release: v0.4.0

---

docs/openapi.json
reana_server/rest/workflows.py
setup.py

* Introducing new rest api endpoing which returns workflow
input parameters. Connects https://github.com/reanahub/reana-client/issues/200

api: new rest api endpoint which returns wf params

---

reana_server/version.py
setup.py

installation: fix pytest-reana dependency version

---

scripts/generate_openapi_spec.py

After generating new OpenAPI specifications, developer needs manually copy them to reana-commons module and docs folder.
This PR introduces new flag --dev. If it is set to TRUE, generated and validated openapi specifications will be copied to reana-commons module and docs folder.
Example of usage.
$ FLASK_APP=reana_server/app.py python ./scripts/generate_openapi_spec.py --dev True
(cherry picked from commit cd155f9d95783c718f7537aadda911be8253754a)

api: automatic openapi specs passing to reana-commons

---

setup.py

* Close reanahub/reana-client#194.

installation: bump reana deps for workflow stop

---

docs/openapi.json
reana_server/rest/workflows.py
scripts/generate_openapi_spec.py
tests/test_views.py

* Closes reanahub/reana-client#210.

api: add remove files from workspace endpoint

---

docs/openapi.json
reana_server/rest/workflows.py
setup.py
tests/test_views.py

* Adds REST API endpoint which calls
reana-workflow-controller to retrieve
a list of differences between two workflows.
Connects https://github.com/reanahub/reana-client/issues/193

rest: workflow diff

---

docs/openapi.json
reana_server/rest/workflows.py
setup.py

* (connects reanahub/reana-workflow-controller#178).

api: add open interactive process endpoint

---

docs/openapi.json
reana_server/rest/workflows.py
setup.py
tests/test_views.py

* Connects reanahub/reana-client/issues/213

api: new endpoint for mv files command

---

Dockerfile
docs/openapi.json
reana_server/rest/workflows.py
setup.py

* Adds endpoint to retrieve disk usage information of
a workflow.
Connects https://github.com/reanahub/reana-client/issues/238

rest: workflow disk usage

---

docs/openapi.json
reana_server/rest/workflows.py
setup.py
tests/test_views.py

Closes https://github.com/reanahub/reana-client/issues/258.

 interactive-execution: predef interactive sessions

---

docs/openapi.json
reana_server/rest/workflows.py
tests/test_views.py

* Connects reanahub/reana-client/issues/247

rest: endpoint for closing an interactive session

---

docs/openapi.json
reana_server/rest/workflows.py
setup.py
tests/test_views.py

* Connects reanahub/reana-client/issues/262

rest: list workflows by type

---

Dockerfile
setup.py

docker: slimmer image

---

reana_server/app.py
reana_server/cli.py
reana_server/factory.py
setup.py

logging: logging format from R-Commons

---

reana_server/cli.py
reana_server/utils.py
setup.py
tests/test_cli.py

cli: add export and import users commands

---

reana_server/cli.py

docs: add import & export users cli docs

---

.travis.yml
AUTHORS.rst
CHANGES.rst
README.rst
docs/conf.py
docs/openapi.json
reana_server/cli.py
reana_server/version.py
setup.py

release: prepare v0.5.0 release

---

docs/openapi.json
reana_server/factory.py
reana_server/rest/secrets.py
reana_server/rest/workflows.py
reana_server/utils.py
reana_server/version.py
setup.py

* Adds endpoints to create, list and delete authenticated user
secrets (addresses #138).

api: endpoints to create, list and delete secrets

---

reana_server/cli.py

Signed-off-by: leticia <leticia.farias.wanderley@cern.ch>

doc: update command that retrieves admin token

---

reana_server/cli.py

Signed-off-by: leticia <leticia.farias.wanderley@cern.ch>

docs: fix email flag on create user command

---

AUTHORS.rst
docs/openapi.json
reana_server/config.py
reana_server/ext.py
reana_server/factory.py
reana_server/utils.py
tests/conftest.py
tests/test_views.py

Signed-off-by: Leticia Farias Wanderley <leticia.farias.wanderley@cern.ch>

auth: set up cern sso endpoints

---

.gitignore
reana_server/config.py
reana_server/rest/gitlab.py
reana_server/rest/workflows.py
reana_server/utils.py
setup.py

Addresses #155
Signed-off-by: Leticia Farias Wanderley <leticia.farias.wanderley@cern.ch>

gitlab: add gitlab endpoints

---

reana_server/config.py

config: restrict allowed hosts to REANA_URL

---

docs/openapi.json
reana_server/rest/gitlab.py
reana_server/rest/secrets.py
reana_server/rest/users.py
reana_server/rest/workflows.py
tests/test_views.py

Addresses reanahub/reana-ui#36

api: add /me blueprint route

---

scripts/setup

setup_script: hides access token from server startup logs

---

scripts/setup

* Adds more message outputs to setup script so that messages can be
caughted and acted upon by reana-dev, make and friends.
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>

scripts: more messages in setup script

---

docs/openapi.json
reana_server/rest/gitlab.py
reana_server/rest/users.py
reana_server/utils.py

gitlab: retrieve information about REANA webhooks

---

reana_server/rest/workflows.py
reana_server/utils.py

workflow: use friendly names

---

reana_server/rest/users.py
reana_server/utils.py
setup.py
tests/test_views.py

addresses reanahub/reana-ui#50

users: add full_name and username to /me endpoint

---

reana_server/config.py

config: add REANA prefix to cache component

---

docs/openapi.json
reana_server/rest/workflows.py
setup.py

addresses reanahub/reana-client#341

api: pass block size param to get disk usage

---

reana_server/utils.py
tests/test_views.py

closes reanahub/reana-client#350

cli: allow uploading empty files

---

reana_server/rest/workflows.py

* Addresses reanahub/reana-client/issues/355

rest: allows to restart workflow

---

reana_server/scheduler.py
tests/test_scheduler.py

* In the event of workflow start up errors (due to DB connections,
failure connecting to Kubernetes etc...) REANA-Server's scheduler
should requeue the workflow, otherwise it will be lost
(closes reanahub/reana#253 #204).

scheduler: requeue workflows when starting failure

---

reana_server/cli.py

logs: add scheduler startup log

---

setup.py

* Addresses reanahub/reana-workflow-controller/issues/289

installation: shared packages version bump

---

reana_server/rest/workflows.py
reana_server/utils.py
setup.py
tests/test_views.py

* Addresses reanahub/reana-workflow-controller/issues/289

rest: changes get_workspace method with workspace_path field

---

reana_server/rest/workflows.py
reana_server/utils.py

* Addresses reanahub/reana-workflow-controller/issues/289

rest: allows to pass WF spec for restart

---

reana_server/rest/workflows.py
setup.py

* `true` and `false` when passed to `bool()` are always true
(closes reanahub/reana-client#367).

rest: load json boolean

---

reana_server/scheduler.py

* Addresses reanahub/reana-client/issues/239

scheduler: not rescheduling deleted workflows

---

reana_server/rest/workflows.py

* Closes reanahub/reana-client/issues/357

rest: return proper message if workflow can't be started

---

docs/openapi.json
reana_server/rest/workflows.py

rest: return workflow progress

---

docs/openapi.json
reana_server/rest/workflows.py
setup.py
tests/test_views.py

* Addresses reanahub/reana-client/issues/369

rest: adds a possibility to query logs for a given step

---

docs/openapi.json
reana_server/rest/workflows.py
reana_server/utils.py
tests/test_views.py

* Returns a reconstruction of the `reana.yaml`, including only
workflow specification, workflow type and input parameters
(closes #219).

rest: add endpoint to return workflow spec

---

docs/openapi.json
reana_server/rest/workflows.py
setup.py
tests/test_views.py

rest: add preview flag to download file

---

docs/openapi.json
reana_server/rest/users.py

closes reanahub/reana-client#383

rest: allow access_token param in /api/me

---

reana_server/ext.py

* Closes #159, closes reanahub/reana-client#358.

ext: add teardown REANA DB session in ext

---

reana_server/rest/workflows.py
reana_server/utils.py
setup.py
tests/test_views.py

rest: return input files and parameters in spec endpoint

---

reana_server/rest/workflows.py

Validates operational options both on creation (reana.yaml options)
and on start (CLI passed options).
closes reanahub/reana-client#396

rest: validate operational options server-side

---

Dockerfile

docker: use uwsgi.ini configuration file

---

Dockerfile
reana_server/reana_admin.py
reana_server/status.py
run-tests.sh
scripts/setup

cli: add stats-report

---

reana_server/factory.py
reana_server/reana_admin.py
reana_server/utils.py
setup.py
tests/conftest.py
tests/test_cli.py
tests/test_views.py

closes #235
To test the email functionality you need to have set the following env vars:
- `REANA_EMAIL_SMTP_SERVER` (smtp.cern.ch)
- `REANA_EMAIL_SMTP_PORT` (587)
- `REANA_EMAIL_LOGIN` (youremaill@cern.ch)
- `REANA_EMAIL_SENDER` (reana-support@cern.ch)
- `REANA_EMAIL_PASSWORD` (yourpassword)

cli: add grant & revoke access token commands

---

docs/openapi.json
reana_server/config.py
reana_server/reana_admin.py
reana_server/rest/users.py
tests/test_cli.py

- Also fixes string duplications in tests
closes reanahub/reana-ui#93

rest: add request token endpoint

---

Dockerfile
reana_server/config.py
reana_server/reana_admin.py
scripts/setup

* This will be used to send daily status reports to REANA admins
(closes reanahub/reana#308).

cli: add email option to status report

---

reana_server/rest/users.py
reana_server/utils.py

rest: return 403 for revoked users

---

docs/openapi.json
reana_server/rest/users.py

rest: group token data on a dict

---

reana_server/utils.py
tests/test_cli.py

cli: export/import username & full name

---

reana_server/config.py

config: use FQDN to access cache

---

CHANGES.rst
docs/openapi.json
reana_server/config.py
reana_server/ext.py
reana_server/rest/users.py
reana_server/rest/workflows.py
reana_server/utils.py
setup.py
tests/test_views.py

closes #256 
closes https://github.com/reanahub/reana-ui/issues/107
ATM, signing in with a too-short password, displays error message "Password length should be between X and Y". This message will disappear once https://github.com/inveniosoftware/invenio-accounts/pull/336 is merged and we update to the latest version.

accounts: support local users

---

docs/openapi.json
reana_server/config.py
reana_server/factory.py
reana_server/rest/config.py
reana_server/rest/users.py
setup.py

rest: add ui config endpoint

---

reana_server/config.py
run-tests.sh
setup.py
tests/conftest.py
tests/test_cli.py
tests/test_scheduler.py
tests/test_views.py

partially addresses reanahub/reana#348
depends on https://github.com/reanahub/pytest-reana/pull/63 https://github.com/reanahub/reana-db/pull/73

tests: move to containerised postgres DB

---

reana_server/config.py

Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>

config: adds removed SQLALCHEMY_DATABASE_URI

---

reana_server/reana_admin.py
scripts/setup

scripts: populate alembic table in setup script

---

reana_server/reana_admin.py
setup.py

cli: catch errors on send_email, give proper msg

---

reana_server/reana_admin.py
reana_server/utils.py

cli: create invenio user in create-admin-user

---

reana_server/rest/users.py

rest: catch email exception on token request endpoint

---

docs/openapi.json
reana_server/rest/users.py
reana_server/rest/workflows.py
requirements.txt
setup.py

rest: expose user disk usage through api

---

docs/openapi.json
reana_server/rest/workflows.py
requirements.txt
setup.py

closes https://github.com/reanahub/reana-ui/issues/132

rest: workflows filtering parameters

---

docs/openapi.json
reana_server/rest/users.py
requirements.txt
setup.py
tests/test_views.py

rest: offer overall user quota consumption

---

reana_server/rest/users.py

This reverts commit 39cd1d1c9db069c548453fd8d49114815d40bbf1.
closes reanahub/reana-db#88

Revert "rest: patch disk quota to return a number"

---

docs/openapi.json
reana_server/rest/config.py

global: fix typo

---

reana_server/rest/workflows.py
reana_server/status.py
requirements.txt
setup.py
tests/test_views.py

closes https://github.com/reanahub/reana-db/issues/89

cli: refactored interactive sessions status for reana-admin

---

docs/openapi.json
reana_server/rest/users.py

rest: return quotas in human readable format

---

reana_server/reana_admin.py
requirements.txt
setup.py

closes #302
```console
$ flask reana-admin quota-resources
processing time
shared storage
$ flask reana-admin quota-set  --email johndoe@example.org  --resource-name 'fake resource' --limit 15000
ERROR: Provided resource name does not exist. Available resources are ['processing time', 'shared storage'].
$ flask reana-admin quota-set  --email johndoe@example.org  --resource-name 'processing time' --limit 15000
Quota limit successfully set. 
```

cli: add command to set limit per user & resource

---

reana_server/status.py

Add quota usage to system status.
closes #286

cli: add quota usage to system status [skip ci]

---

reana_server/decorators.py
reana_server/reana_admin.py
reana_server/rest/gitlab.py
reana_server/rest/secrets.py
reana_server/rest/users.py
reana_server/rest/workflows.py
reana_server/utils.py
requirements.txt
setup.py
tests/test_views.py

rest: prevent workflows from running when quota is exceeded

---

reana_server/reana_admin.py

Add check to see if the only user is the admin user. If so skip computing the quota usage.
closes #313

cli: skip quota usage check if only admin user

---

docs/openapi.json
reana_server/rest/users.py
requirements.txt
setup.py

closes https://github.com/reanahub/reana-client/issues/441

rest: return reana_server url

---

CHANGES.rst
reana_server/rest/gitlab.py
reana_server/utils.py

gitlab: fix fetching projects with other webhooks

---

reana_server/rest/workflows.py

closes reanahub/reana-workflow-controller#339

api: prevent disk quota excess on file upload

---

.flake8
.github/workflows/ci.yml
Dockerfile
MANIFEST.in
reana_server/reana_admin.py
reana_server/rest/workflows.py
reana_server/utils.py
run-tests.sh
setup.py
tests/test_factory.py

addresses https://github.com/reanahub/reana/issues/450

ci: add hadolint and flake8 linters

---

.github/workflows/ci.yml
Dockerfile
docs/conf.py
docs/openapi.json
reana_server/rest/config.py
setup.py

api: control ui signup form visibility with through config endpoint

---

docs/openapi.json
reana_server/rest/workflows.py

closes reanahub/reana-client#225

rest: support glob patterns when listing files

---

CHANGES.rst
docs/openapi.json
reana_server/rest/workflows.py

Depends on https://github.com/reanahub/reana-server/pull/345
closes reanahub/reana-client#402

download: propagate content-disposition header

---

reana_server/status.py

closes https://github.com/reanahub/reana-workflow-controller/issues/363

cli: add pending workflows to status summary

---

.github/workflows/ci.yml
CHANGES.rst
docs/openapi.json
reana_server/rest/users.py
reana_server/rest/workflows.py
requirements.txt
setup.py

performance optimisations for list command
closes https://github.com/reanahub/reana-client/issues/510

list: add --include-progress and --include-workspace-size

---

reana_server/scheduler.py

closes #364
1. Set a custom `REANA_MAX_CONCURRENT_BATCH_WORKFLOWS` and run some workflows. 
1. Verify that the number of workflows running is never greater than the limit.
2.1. `kubectl get pods | grep reana-run-batch`
2.2. In the UI `/status`

scheduler: consider pending wfs to check max concurrent

---

reana_server/complexity.py
reana_server/rest/workflows.py
tests/test_complexity.py

rest: move complexity priority calculation to r-db

---

reana_server/scheduler.py

Optimises SQL query to count running or pending workflows. Avoids ORM
technique that would lead to subselects.
Closes DB session explicitly. This fixes observed "idle in transaction"
issues.

scheduler: fix query counting running workflows

---

CHANGES.rst
reana_server/config.py
reana_server/scheduler.py
setup.py
tests/conftest.py
tests/test_scheduler.py

Depends on: https://github.com/reanahub/reana-commons/pull/266
Closes https://github.com/reanahub/reana-server/issues/118

scheduler: delay rescheduled workflows and count number of retries

---

reana_server/rest/gitlab.py
reana_server/rest/workflows.py
reana_server/utils.py

closes https://github.com/reanahub/reana-server/issues/368
This PR needs to be tested on dev instance in order to make sure that Gitlab integration works as expected

gitlab: load yadage spec and calculate workflow complexity

---

reana_server/complexity.py

closes https://github.com/reanahub/reana-workflow-engine-yadage/issues/188

complexity: make compatible with yadage string-like resources

---

CHANGES.rst
reana_server/complexity.py
reana_server/config.py
reana_server/rest/workflows.py
reana_server/utils.py
tests/test_complexity.py

closes https://github.com/reanahub/reana-server/issues/357
Depends on: https://github.com/reanahub/reana-commons/pull/271

complexity: take into account workflow scheduling policy

---

reana_server/config.py

Fixes casting of Helm values that were read as strings but that should
be treated as integers.

config: fix helm value casting

---

reana_server/status.py
requirements.txt
setup.py

Closes https://github.com/reanahub/reana/issues/512

release: 0.8.0a2

---

CHANGES.rst
docs/openapi.json
reana_server/config.py
reana_server/scheduler.py
reana_server/version.py
tests/test_scheduler.py

closes https://github.com/reanahub/reana-server/issues/382

scheduler: delay workflow consumption

---

reana_server/scheduler.py
setup.py
tests/conftest.py
tests/test_scheduler.py

Depends on: https://github.com/reanahub/reana-commons/pull/272

scheduler: remove retry_count from workflow submission event handler

---

reana_server/rest/workflows.py

closes https://github.com/reanahub/reana-client/issues/522

api: add search param in get_workflow_disk_usage

---

reana_server/config.py
reana_server/rest/workflows.py
requirements.txt
setup.py

closes reanahub/reana-client#531

snakemake: support workflow type

---

AUTHORS.rst
reana_server/utils.py
requirements.txt
setup.py

utils: create full user_workspace_path stored in the database

---

reana_server/complexity.py

closes https://github.com/reanahub/reana-server/issues/375
Improve complexity estimation to take into account workflow nesting and scatter-gathering for CWL workflows.
In order to test:
- Place `wdb` breakpoint [here](https://github.com/reanahub/reana-server/blob/master/reana_server/utils.py#L111) after `complexity = _calculate_complexity(workflow)`
- Change `fifo` value to something else in [this line](https://github.com/reanahub/reana-server/blob/master/reana_server/utils.py#L105) in order to skip the `if statement`
- Launch any `cwl` workflow and inspect the estimated complexity inside the debugger
- Also I've created this [test workflow](https://github.com/audrium/reana-demo-scattered-helloworld/blob/master/workflow/cwl/helloworld.cwl) - extended version of `helloworld demo` which …

complexity: improve complexity estimation for scatter-gathered CWL workflows

---

docs/openapi.json
reana_server/rest/workflows.py

Closes reanahub/reana-client#452

workflows: introduce -w option in list command to filter over a specific workflow

---

reana_server/config.py
tests/test_config.py

- gets API limiter configuration from env
- validates if limiter configuration is in correct format
closes #404

config: get API limiter configuration from env

---

CHANGES.rst
docs/openapi.json
reana_server/complexity.py
reana_server/config.py
reana_server/rest/status.py
reana_server/status.py
tests/test_complexity.py

closes https://github.com/reanahub/reana-ui/issues/206

rest: improve cluster health status calculation

---

reana_server/rest/workflows.py

* the `preview` query param must contain a `true` value to consider it True.
* when `Content-Disposition` header is set, even if its content is empty,
is not possible to preview eg. HTML directly on the server, thus we set this
header only when it's needed (downloads).
closes reanahub/reana-ui#190

rest: include `Content-Disposition` header when needed

---

CHANGES.rst
reana_server/rest/workflows.py
requirements.txt
setup.py

closes https://github.com/reanahub/reana-client/issues/584

rest: added workspace name validation to the create_workflow endpoint

---

CHANGES.rst
docs/openapi.json
reana_server/config.py
reana_server/rest/info.py
requirements.txt
scripts/generate_openapi_spec.py
setup.py

closes reanahub/reana-workflow-controller#424

rest: return supported compute backends in info endpoint

---

requirements.txt
setup.py

closes #429
**Note:** before merging this PR, [r-commons](https://github.com/reanahub/reana-commons/pull/332) need to be updated.

installation: bump shared modules

---

CHANGES.rst
docs/conf.py
docs/openapi.json
reana_server/factory.py
reana_server/rest/launch.py
setup.py

rest: add new `/launch` blueprint and route

---

reana_server/fetcher.py
tests/test_fetcher.py

Closes #459 
How to test:
Launch the following workflows
- https://github.com/cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysis/tree/2012
- https://github.com/cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysis/tree/v1.3
- https://github.com/cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysis/tree/4eb69e073d3b2567c49b2525c2a53341a16dc1ab
Expected result: All the workflows are successfully launched and executed

fetcher: fix fetching of Git repositories

---

reana_server/rest/launch.py

closes https://github.com/reanahub/reana-server/issues/456

rest: specify workspace path while loading spec in launch endpoint

---

reana_server/fetcher.py
tests/test_fetcher.py

Closes #453
How to test:
Launch the following workflows
- https://github.com/cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysis/archive/refs/heads/2012.zip
- https://github.com/cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysis/archive/refs/tags/v1.3.zip
- https://github.com/cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysis/archive/4eb69e073d3b2567c49b2525c2a53341a16dc1ab.zip
Expected result: the names of the workflows launched contain the name of the repo

fetcher: improve workflow naming for zip archives from GitHub

---

reana_server/rest/launch.py
reana_server/rest/workflows.py
reana_server/utils.py

Closes #463
How to test:
1. Launch one of the demo examples, e.g. [reana-demo-helloworld](https://github.com/reanahub/reana-demo-helloworld/), and check that the user's disk quota is updated before the workflow has finished its execution
2. After the execution of the workflow, set the user's disk quota to a value that is less than his current disk usage
3. Launch one of the demo examples and check that the workflow is not launched, given that the user has exceeded his quota
4. Set the user's disk quota to a value that is just one byte more than his current disk usage
5. Launch one of the demo example and check that the workflow is not launched, given that launching the workflow would exceed the user's disk quota

rest: check and update quotas in `/launch` endpoint

---

reana_server/rest/workflows.py
reana_server/utils.py

- fix GitLab integration for CWL and Snakemake workflows;
closes #474

rest: workflows, fix GitLab integration for CWL and Snakemake

---

CHANGES.rst
docs/openapi.json
reana_server/ext.py
requirements.txt
setup.py
tests/conftest.py

closes https://github.com/reanahub/reana-server/issues/479

setup: upgrade invenio dependencies

---

reana_server/scheduler.py
requirements.txt
setup.py

Closes reanahub/reana-workflow-engine-snakemake#44

scheduler: stop retrying if request to r-w-controller is not valid

---

reana_server/rest/launch.py
reana_server/utils.py
reana_server/validation.py
tests/test_utils.py
tests/test_validation.py

Closes #492
How to test:
1. Launch one of the demo examples, e.g. `reana-demo-helloworld`
2. Check that only the files and directories specified in `reana.yaml` are present in the workspace

launcher: remove unnecessary files after fetching

---

AUTHORS.rst
CHANGES.rst
reana_server/rest/workflows.py
reana_server/utils.py

closes #495
We do not have a local Gitlab integration, so you cannot test. Currently, this branch is deployed on production, so you can try to run some Gitlab workflow ([how to](https://docs.reana.io/advanced-usage/code-repositories/gitlab/)).
Test if `r-client` works as it was working before.

rest: fail Gitlab commit if quota is exceeded

---

docs/openapi.json
reana_server/rest/workflows.py

Updates the openapi disk usage specification, so that it can be more useful in `reana-client-go`

openapi: updated disk usage api schema

---

docs/openapi.json
reana_server/rest/config.py
reana_server/rest/gitlab.py
reana_server/rest/info.py
reana_server/rest/launch.py
reana_server/rest/secrets.py
reana_server/rest/status.py
reana_server/rest/users.py
reana_server/rest/workflows.py

closes https://github.com/reanahub/reana-client-go/issues/16

openapi: add missing schemas to error responses

---

CHANGES.rst
docs/openapi.json
reana_server/config.py
reana_server/rest/info.py
requirements.txt
scripts/generate_openapi_spec.py
setup.py

- add kubernetes default and max memory limits;
- add default workspace retention period.
closes reanahub/reana-client#622

rest: add new default values to "info" endpoint output

---

docs/openapi.json
reana_server/rest/workflows.py

closes https://github.com/reanahub/reana-client-go/issues/93

openapi: add missing param schema do set_workflow_status

---

docs/openapi.json
reana_server/rest/workflows.py

closes https://github.com/reanahub/reana-client-go/issues/96

openapi: fix response schema of delete_file()

---

docs/openapi.json
reana_server/rest/workflows.py

closes https://github.com/reanahub/reana-client-go/issues/97

openapi: add missing response to move_files

---

requirements.txt
setup.py
tests/conftest.py
tests/test_cli.py

Closes reanahub/reana-commons#379

admin: support recursive globbing in `retention-rules-apply`

---

docs/openapi.json
reana_server/rest/workflows.py
requirements.txt
setup.py
tests/test_views.py

Closes https://github.com/reanahub/reana-workflow-controller/issues/485

rest: add `get_workflow_retention_rules` endpoint

---

docs/openapi.json
reana_server/rest/workflows.py
reana_server/validation.py
reana_server/version.py
tests/test_validation.py

closes https://github.com/reanahub/reana-client/issues/626

rest: validate inputs on workflow creation

---

CHANGES.rst
docs/openapi.json
reana_server/rest/gitlab.py

gitlab: fix redirect after successful authorization

---

docs/openapi.json
reana_server/version.py
requirements.txt
setup.py

- installation: bump shared modules
- release: 0.9.1a2

release: 0.9.1a2

---

CHANGES.rst
reana_server/config.py

config: add REANA_GITLAB_HOST to the allowed GitLab instances

---

docs/openapi.json
reana_server/version.py
requirements.txt
setup.py

- installation: bump shared modules
- release: 0.9.1a3

release 0.9.1a3

---

CHANGES.rst
reana_server/scheduler.py

scheduler: expose scheduling errors to users

---

CHANGES.rst
Dockerfile
MANIFEST.in
docs/openapi.json
reana_server/version.py
requirements.txt
setup.py

release: 0.9.2

---

run-tests.sh

ci(pytest): move to PostgreSQL 14.10 (#672)

---

.github/workflows/ci.yml
.prettierignore
.prettierrc.yaml
.release-please-config.json
CONTRIBUTING.md
MANIFEST.in
README.md
docs/index.md
run-tests.sh

Also add .prettierignore for ignored files and .prettierrc.yaml for standard print width.

ci(prettier): add Prettier code formatting checks (#737)
